version: '3.9'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    container_name: mysql
    ports:
      - 3306:3306
    networks:
      - go_net

  wait-for-db:
    image: atkrad/wait4x
    depends_on:
      - db
    command: tcp db:3306 -t 40s -i 250ms
    networks:
      - go_net

  application:
    image: TODOIMAGE
    ports:
     - 8080:8080
    depends_on:
      wait-for-db:
        condition: service_completed_successfully
    container_name: golang-api
    networks:
      - go_net
    volumes:
      - .env:/.env

networks:
  go_net:
    driver: bridge