version: '3'
services:
  database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_DATABASE: ${DB_NAME}
    container_name: mysql
    ports:
      - 3306:3306
    networks:
      - go_net

  application:
    #build:
    #  context: .
    #  dockerfile: ./Dockerfile
    image: TODOIMAGE
    ports:
     - 8080:8080
    depends_on:
     - database
    container_name: golang-api
    networks:
      - go_net
networks:
  go_net:
    driver: bridge